# Generated by Django 3.2.6 on 2021-08-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emil',
            new_name='email',
        ),
    ]
